### ISSUE TITLE
Providing Name/Email in Sender Options overrides on HTML Emails

### ISSUE THREAD

**Issue by garrett-eclipse** [nlemoine/wp-better-emails#14]
WP Ticket - https://wordpress.org/support/topic/providing-nameemail-in-sender-options-overrides-on-html-emails?replies=1#post-7873290

*Posted here as I'll be forking and fixing.

**Comment by nlemoine** [comment]
Hi @garrett-eclipse, 

> These sender options should only come into effect on plain text emails as they're the only ones to be picked up by the plugin.

Actually, no. The plugin picks up every email sent as plain text. Using sender email and sender name isn't related to templating at all and it overrides any values set by other code. Meaning it overrides values when sending a comment notification for example. See this thread: https://wordpress.org/support/topic/plugin-wp-better-emails-please-make-the-sender-email-and-name-optional

I should probably add a warning about using this feature.

**Comment by garrett-eclipse** [comment]
Thanks @nlemoine,
You mentioned 'The plugin picks up every email sent as plain text', which makes sense. But the Sender Options seem to be affecting HTML emails which shouldn't be affected by the plugin correct? It should only function on plain text emails that are converted to HTML.
My fix was to have these Sender Options only affect those plain text emails that the plugin are picking up and converting to HTML.
Hope that makes sense,
Cheers

**Comment by nlemoine** [comment]
> But the Sender Options seem to be affecting HTML emails which shouldn't be affected by the plugin correct?

The plugin is about templating. Setting sender name and email is an optional additional feature that has nothing to do with templating. These options applies whether the email is plain text or HTML. 
It does not really make sense to turn on this feature on plain text only. I don't know if it's clear.

**Comment by garrett-eclipse** [comment]
Thanks @nlemoine the latest changes you made in 0.3 and discussed in my WP Ticket (https://wordpress.org/support/topic/providing-nameemail-in-sender-options-overrides-on-html-emails?replies=3#post-7922727) have resolved my issue as I'd wanted the from information coming from plugins such as woocommerce to be unaffected which is now the case.
Cheers
