### ISSUE TITLE
Admin message contextual_help is deprecated since version 3.3.0

### ISSUE THREAD

**Issue by wdfee** [nlemoine/wp-better-emails#24]
Hi there, I'd appreciate it if the plugin would be developed further. Here's a current bug with fix:
see https://wordpress.org/support/topic/admin-message-contextual_help-is-deprecated-since-version-3-3-0/

After the update to WordPress 5.4 we get a message in all /wp-admin pages:
> Deprecated: contextual_help is deprecated since version 3.3.0! Use get_current_screen()->add_help_tab(), get_current_screen()->remove_help_tab() instead. in /[...]/wp-includes/functions.php on line 5089

Fix: change line #82 in wpbe.php from
`add_filter( 'contextual_help',      array( $this, 'contextual_help' ), 10, 3 );`
to
`add_action( 'add_help_tab',      	array( $this, 'contextual_help' ), 10, 3 );`

**Comment by CreativForm** [comment]
I made update on my repo for that, you can download and replace your plugin files.

It seams that author not maintain plugin as long time and I take care on my side until is solved by author.

https://github.com/CreativForm/wp-better-emails

**Comment by nlemoine** [comment]
I juste released 0.4 that fixes this.

**Comment by InfinitumForm** [comment]
> I juste released 0.4 that fixes this.

That's great! Thank you!
