### ISSUE TITLE
Update repo to match WP release v2.8

### ISSUE THREAD

**Issue by r-a-y** [nlemoine/wp-better-emails#3]
Hi nlemoine,

Some changes in v2.7 broke some custom implementations of WP Better Emails that we've been using.

Can you update the Github repo so the latest changes from v2.7 are on Github?  Then, I can send some pull requests.

Thanks!

**Comment by r-a-y** [comment]
Thanks for updating.  Can you re-update the repo so it matches the latest version?

I still have a pull request I'd like to send :)

**Comment by r-a-y** [comment]
Any update here?

**Comment by nlemoine** [comment]
Sorry for the late update.
