### ISSUE TITLE
Add ability to hook into the template processing and filter template before email is out

### ISSUE THREAD

**Issue by nekojira** [nlemoine/wp-better-emails#4]
How about using a php template instead the hard-coded html in the TinyMCE box?

suppose one wants to skip the html template as appears in the TinyMCE box, perhaps conditionally, one should be able to filter the message before is sent out by WPBE and change its html contents while retaining the contents of the %content% variable.

this would be handy if one were to re-use the same template with other plugins that make use of html email (e.g. WooCommerce) or fill template parts with variables, which is currently restricted to WPBE own template tags at the moment.

Could you provide a filter hook in `process_email_html( $message )` function and `process_email_text( $message )` while returning the message at the end of the function please? (or elsewhere you think it's best suitable) You could pass %content% for use as filter argument.

Thanks

**Comment by nekojira** [comment]
oh never mind, sorry I just realized there are already in place

`add_filter( 'wpbe_html_body', 'your_html_template', 10, 1 );`

`add_filter( 'wpbe_plaintext_body, 'your_plaintext_template', 10, 1 );`

I realize they pass the whole message including all the html tags set in the TinyMCE html - however if this is just %content% then only the message body will be passed

cool

**Comment by nlemoine** [comment]
Cool.
