### ISSUE TITLE
Email sent using this plugin is rejected by AOL

### ISSUE THREAD

**Issue by mattvick** [nlemoine/wp-better-emails#5]
Web server email logs show the following error message: "X=TLSv1:DHE-RSA-AES256-SHA:256: SMTP error from remote mail server after end of data: 521 5.2.1 :  AOL will not accept delivery of this message."

This has been tested sending to both @aol.com and @aol.co.uk email addresses.

The issue appears to be the HTML in the template

**Comment by hubdotcom** [comment]
Can you confirm it works without the plugin activated? Are you using the default name and email address or custom ones?
